wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.9
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693467412.686594
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 103
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 103
      3:
      - 7
      - 13
      - 23
      4: 3.10.9
      5: 0.15.9
      6: 4.24.0
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
num_classes:
  desc: null
  value: 1
dropout:
  desc: null
  value: 0.1
lr:
  desc: null
  value: 5.0e-05
num_train_epochs:
  desc: null
  value: 20
warmup_steps:
  desc: null
  value: 1000
